POST http://localhost:3001/1.0/login/
content-type: application/json

{
    "correo": "ald@gmail.com",
    "contrasenia": "12345"
}

###

POST http://localhost:3002/1.0/productos/modificarEstado/1
content-type: application/json

{
    "nuevo_estado": 1,
    "nuevo_descuento":5,
    "nueva_categoria": null
}




###

POST http://localhost:3001/1.0/register/
content-type: application/json

{
    "run": "20749760-6",
    "nombre": "Aldo Arroyo",
    "correo": "ald@gmail.com",
    "contrasenia": "12345",
    "es_empleado": false,
    "cod_especialidad": ""
}

